name: ncurses-idris tests
on: 
  push:
    branches:
      - main
  pull_request:
#  schedule:
#    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:nightly

    env:
      IDRIS2_CG: chez

    steps:
      - name: Install Dependencies
        run: apt-get update && apt-get -y install git libncurses-dev libc6-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ncurses-idris
        run: make && make install
      - name: Build doc example
        run: |
          cd examples/doc_ann
          make
          cd -
      - name: Build control example
        run: |
          cd examples/control_curses
          make
          cd -

