name: ncurses-idris tests
on: 
  push:
    branches:
      - main
  pull_request:
#  schedule:
#    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:nightly

    env:
      IDRIS2_CG: chez
      NCURSES_VERSION: 6

    steps:
      - name: Install Dependencies
        run: apt-get update && apt-get -y install git libncurses-dev libc6-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ncurses-idris
        run: make && make install
      - name: Build doc example
        run: |
          cd examples/doc_ann
          make
          cd -
      - name: Build control example
        run: |
          cd examples/control_curses
          make
          cd -
      - name: Build timed example
        run: |
          cd examples/timed
          make
          # I would like to run this here, but it fails in GitHub CI which I assume
          # is somehow because the terminal can't support ncurses.
          # ./build/exec/timed
          # Instead, let's just check for some of the artifacts in the right locations:
          ldd ./build/exec/timed_app/timed.so
          if [[ ! -d "./depends/ncurses-idris-0/lib" ]]; then
            echo 'depends or lib dir missing.'
            exit 1
          fi
          if [[ ! -f "./depends/ncurses-idris-0/lib/libncurses-idris.so" ]]; then
            echo 'libncurses-idris.so missing for depends.'
            exit 1
          fi
          if [[ ! -f "./depends/ncurses-idris-0/NCurses.ttc" ]]; then
            echo 'TTC files missing.'
            exit 1
          fi
          if [[ ! -f "./build/exec/timed_app/libncurses-idris.so" ]]; then
            echo 'libncurses-idris.so missing for build dir.'
            exit 1
          fi
          cd -

